### ISSUE TITLE
schedule create?

### ISSUE THREAD

**Issue by JonhnyDev** [upstash/sdk-qstash-ts#11]
Hey guys...
I have a question about schedule jobs in Qstash:
https://docs.upstash.com/qstash/features/schedules

The CronJobs is create only with API REST
"curl -XPOST \
    -H 'Authorization: Bearer XXX' \
    -H "Content-type: application/json" \
    -H "Upstash-Cron: * * * * *" \
    -d '{ "hello": "world" }' \
    'https://qstash.upstash.io/v1/publish/https://example.com'"

because is not possible with SDK? 
or is possible but I didn't find it?

API doc has (get, list and delete only):
https://docs.upstash.com/qstash/openapi#tag/Schedules

**Comment by chronark** [comment]
@JonhnyDev 
it's a field called `cron`

```ts
client.publish({
  // ...
  cron: "* * * * *"
})
```

And the api docs for schedules don't include this, because you create a schedule, by publishing a regular message and adding the `Upstash-Cron` header.
I'll make that more clear in the future, thanks for the feedback.

**Comment by JonhnyDev** [comment]
Working, Thank you

**Comment by elie222** [comment]
I see it became this now:

```ts
  return await client.schedules.create({
    cron,
    destination: url,
  });
  ```
