### ISSUE TITLE
does sending header to destination supported?

### ISSUE THREAD

**Issue by rebaz94** [upstash/sdk-qstash-ts#12]
Hi.
I want to send custom header to my destination but after checking the logs, it seems that does not sent anything. Also I can't find a way to set basic auth for testing because `Authorization` should be the `Qstash token`.

**Comment by chronark** [comment]
You can check how to send custom headers [here](https://docs.upstash.com/qstash/howto/publishing#sending-custom-http-headers)

why do you need basic auth?
qstash does not work with basic auth

**Comment by rebaz94** [comment]
@chronark Thank you for the link.

I just tested it and work perfectly.
```
'Upstash-Forward-My-Header': 'rebaz'
```


> qstash does not work with basic auth

I used it only for testing with ngrok, and passing basic auth in header like
```ngrok http --basic-auth="user:password" 4000```

and then just forward the basic auth to ngrok make it work.
```
'Upstash-Forward-Authorization': 'Basic dXNlcjpwYXNzd29yZA=='
```

**Comment by rebaz94** [comment]
I just close the issue. Thank you for your quick response.
