### ISSUE TITLE
Retrying problem with failed request

### ISSUE THREAD

**Issue by rebaz94** [upstash/sdk-qstash-ts#13]
Hi,
I have two problem when request failed.

**1. When I send a request with specified ```Upstash-Retries``` header, the Upstash will retry failed request more than specified retries.**

for example I set 3 retries and at first the console shows correct retrying number like 2/3 but after some time it will send another request which will be 4 request in total.

<img width="525" alt="Screen Shot 2022-10-13 at 2 52 38 PM" src="https://user-images.githubusercontent.com/11982812/195589120-a92df76b-3b0d-41b8-a11f-a7de224f6702.png">

**2. When I send a request with specified ```Upstash-Deduplication-Id``` header and the request is failed, I can't publish new message with same id, even if all request is already failed, it will ignore the message.**

does it's expected? or how I publish new message that has same failed id but start from scratch?

Thank you

**Comment by chronark** [comment]
1. Retries are counted after the first delivery fails, it's not the total number of attempts made
2. That's how deduplication works, it just prevents you from publishing the same message twice, it does not make any guarantees about successful delivery

**Comment by rebaz94** [comment]
>We'll make the deduplication window configurable soon, currently it's set to 90 days

You mean by configuring window time for example 5 minute, after that you can publish message with same id?

**Comment by rebaz94** [comment]
@chronark do you have any api to get number of failed request for a specified message? or you need to use ```logs``` api and manually calculate failed request?

**Comment by chronark** [comment]
Yes you could set it to X minutes/hours/days and afterwards you can reuse the ID.


No currently the logs is all there is.

**Comment by rebaz94** [comment]
Thank you for clarification.

**Comment by gprieto** [comment]
>    We'll make the deduplication window configurable soon, currently it's set to 90 days

Any updates on this?
