### ISSUE TITLE
schedules.delete tries to parse non json response

### ISSUE THREAD

**Issue by HaNdTriX** [upstash/sdk-qstash-ts#14]
## Current Behavior

When invoking `client.schedules.delete({ id: scheduleId })` with an active/valid `scheduleId` the client throws an exception but also deletes the schedule entry from the system: 

```error
invalid json response body at https://qstash.upstash.io/v1/schedules/{scheduleId}
...
```

## Expected Behavior

When invoking `client.schedules.delete({ id: scheduleId })` with an active/valid `scheduleId` the client should not throw an exception.

## Example Code

```js
const client = new Client({
  token: "{QSTASH_TOKEN}",
});

await client.schedules.delete({ id: '{scheduleId}' })
// => throws new Error("invalid json response body at https://qstash.upstash.io/v1/schedules/{scheduleId}")
```

**Comment by chronark** [comment]
👍 thank you
I'll fix the response on the server and deploy it today

**Comment by chronark** [comment]
Hey just a heads up:
we discovered a different issue which blocks the deployment right now.
The changes here should be deployed early next week though.
