### ISSUE TITLE
Trying to cancel a task

### ISSUE THREAD

**Issue by LeandroParisi** [upstash/sdk-qstash-ts#19]
Hello I am using QStash to process some async events.
But I have to do a idempotency check and, if it fails I wanted to delete the message since it was alredy processed.

Tried doing it with the following method:
```
await qStashClient.messages.delete({
    id: messageId,
  })
```
But got this error:

`QstashError: {"error":"error deleting task from queue: asynq: FAILED_PRECONDITION: cannot delete task in active state. use CancelTask instead."}`

Wasn't able to find this CancelTask method, is it not implemented on this sdk yet?

**Comment by chronark** [comment]
Fixed in v2
