### ISSUE TITLE
Add a working example of nextjs edge functions on Vercel

### ISSUE THREAD

**Issue by spyl94** [upstash/sdk-qstash-ts#22]
It would be great to have an example of qstash `verifySignature` inside a [Vercel Edge Fuctions](https://vercel.com/docs/concepts/functions/edge-functions/quickstart).

The README say it's supported but I'm getting `Error: The edge runtime does not support Node.js 'crypto' module.` error. (https://nextjs.org/docs/messages/node-module-in-edge-runtime)

```ts
import { verifySignature } from '@upstash/qstash/nextjs';

export const config = {
  runtime: 'experimental-edge',
  api: {
    bodyParser: false,
  },
};

const handler = async () => {
  console.log('If this is printed, the signature has already been verified');
};

// @ts-expect-error edge is not supported yet by TS types
export default verifySignature(handler);
```

**Comment by chronark** [comment]
Hey @spyl94.
The [Receiver](https://github.com/upstash/sdk-qstash-ts/blob/main/pkg/receiver.ts#L56) 
Should work in edge functions.

`verifySignature` is a nextjs specific syntactic sugar for regular serverless function.
Even if it didn't use nodejs specifics, it would not be compatible with the signature of an edge function handler.


I'm curious why do you want to run this at the edge?
I doubt latency is your motivation here.

**Comment by spyl94** [comment]
Thanks, I will try to implement my own `verifySignature` for edge functions.

My main motivation is that edge functions are a lot cheaper to run than serverless functions (https://vercel.com/docs/concepts/limits/overview#functions-comparison), and powerful enough to consume a single message !

**Comment by spyl94** [comment]
I tried to use : 

```ts
import { Receiver } from '@upstash/qstash/nodejs';

const receiver = new Receiver({
    currentSigningKey,
    nextSigningKey,
    subtleCrypto: crypto.subtle,
});
```

But I still got the `The edge runtime does not support Node.js 'crypto' module.` error. 

So instead I had to rewrite without the SDK : https://gist.github.com/spyl94/f49f4bb34aa1c3fec724de7c40f82f78

**Comment by chronark** [comment]
Hmm. I would've assumed that something like this should work: https://github.com/upstash/sdk-qstash-ts/tree/main/examples%2Fcloudflare-workers

Since vercel edge is built on CF workers

**Comment by chadedrupt** [comment]
This is causing issues for me in a plain Node.js backed server less functions.
Suspecting this is what's causing it https://github.com/upstash/sdk-qstash-ts/blob/66b1c18fc19e0a93ae5dd70a4f653a9a3b9e3651/pkg/receiver.ts#L2

**Comment by pencilcheck** [comment]
might be related as crypto isn't supported in node 14. it looks like qstash is assuming node 16+ which is not possbile due to the library dependencies

**Comment by chronark** [comment]
@chadedrupt what node version are you on?
as @pencilcheck said, this is probably due to node 14

**Comment by chronark** [comment]
https://github.com/upstash/sdk-qstash-ts/tree/main/examples/nextjs
this example now has
- serverless function
- edge function
- route (app router)
