### ISSUE TITLE
Typescript errors with Vercel serverless functions

### ISSUE THREAD

**Issue by vitoraguila** [upstash/sdk-qstash-ts#35]
I'm getting some typescript errors

Node version: 18
Typescript: latest version

<img width="744" alt="image" src="https://github.com/upstash/sdk-qstash-ts/assets/22822385/35aacc99-9605-41b0-b8b9-5b8a4dc11630">

any idea?

**Comment by chronark** [comment]
What sdk version?

**Comment by vitoraguila** [comment]
@chronark     
`"@upstash/qstash": "^0.3.6"`

**Comment by chronark** [comment]
fixed in v2+
