### ISSUE TITLE
Logs method is not working

### ISSUE THREAD

**Issue by bastienrobert** [upstash/sdk-qstash-ts#41]
The logs method in the client is not working: https://github.com/upstash/sdk-qstash-ts/blob/main/pkg/client/client.ts#L306-L311

It looks like the `/v1/logs` endpoints doesn't exists anymore. Maybe it has been renamed [`tasks`](https://docs.upstash.com/qstash/openapi#tag/Tasks)?

**Comment by chronark** [comment]
ah, good catch
it's `/v1/events`

I'll work on a few of these issues next week

**Comment by chronark** [comment]
`v2` has this fixed 
```ts
 qstash.events(req?: EventsRequest): Promise<GetEventsResponse>
 ```
