### ISSUE TITLE
Why is notBefore and delay in seconds and not milliseconds?

### ISSUE THREAD

**Issue by kristianeboe** [upstash/sdk-qstash-ts#42]
I kept getting errors when using the SDK that I was trying to delay a message more than a year, when i finally found in your SDK docs that you expect delay and notBefore in seconds.
![image](https://github.com/upstash/sdk-qstash-ts/assets/10433154/7066d43a-14af-4b36-8cb0-68ce7c2179fe)

Most JS dates and durations operate with milliseconds, wouldn't that be a simpler standard for you too? 

I'm trying to do this now 🤞 
![image](https://github.com/upstash/sdk-qstash-ts/assets/10433154/d60b5851-6961-4fb0-8f7b-cc0e9d21543d)

**Comment by chronark** [comment]
Yeah, fair point
it was mostly because I thought delaying <1s wouldn't be accurate anyways.

JS does handle everything in milliseconds, but that's not necessarily true for all other languages, so there isn't a clear path forward.
