### ISSUE TITLE
Deleting Schedules Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by msywulak** [upstash/sdk-qstash-ts#52]
Attempting to delete a schedule throws an error `Error: Unexpected end of JSON input` due to a res.json() being expected but not provided by the server. 

In `http.ts` a response is expected `return (await res.json()) as UpstashResponse<TResult>;` but the server does not respond with one, so the above error is thrown.

**Comment by msywulak** [comment]
#54 added `parseResponseAsJson?: boolean;` which fixes this issue

**Comment by msywulak** [comment]
Spoke too soon - that property was added but not utilized by schedules. Added it to #55

**Comment by chronark** [comment]
fixed in v2.1.6
