### ISSUE TITLE
Method Not Allowed - Problem using v2

### ISSUE THREAD

**Issue by fmoessle** [upstash/sdk-qstash-ts#58]
Hi!

I am trying to upgrade to v2 using the npm package ``` "@upstash/qstash": "2.1.6"```

I want to add an endPoint to an existing topic but I only get: ```Method Not Allowed```

```ts
await qstash.topics.addEndpoints({
  endpoints: [{ url: `http://test.com` }],
  name: 'name_of_my_endpoint',
})
```

It seems no documentation for v2 npm package exists?

**Comment by chronark** [comment]
whoops, releasing `v2.1.7` right now
