### ISSUE TITLE
Improving the documentation

### ISSUE THREAD

**Issue by callum-gander** [upstash/sdk-qstash-ts#75]
This is a super simple issue, please improve your documentation for this SDK. Your documentation on your website doesn't use it and reading parts of the code itself doesn't make much clearer, e.g. how do you create a schedule? 

This is a huge red flag for new users coming to this project, they shouldn't have to dig into the code to make sense of what to do, I think we'd all really appreciate you guys putting sometime into updating the documentation with how to do everything with this SDK you clearly put a lot of work into. Thanks in advance

**Comment by fahreddinozcan** [comment]
Hey, thank you for the feedback and I think you're right. I will raise this issue internally, and we'll make sure to improve the documentation by covering the features and cases.

**Comment by MeshanKhosla** [comment]
Hi, we just added a ton of examples for the SDK here:
https://upstash.com/docs/oss/sdks/ts/qstash/overview

It goes over an overview, getting started, and a bunch of examples. Let us know what you think!

**Comment by callum-gander** [comment]
Amazing! This is exactly what I wanted, thanks for adding this!
