### ISSUE TITLE
client.topics is not a function

### ISSUE THREAD

**Issue by mankins** [upstash/sdk-qstash-ts#77]
I'm attempting to migrate from v1 to v2 and to do that wanted to access the topics api, following the examples [here](https://upstash.com/docs/oss/sdks/ts/qstash/examples/topics).

Unfortunately with the examples above, this line:

```
      const topics = client.topics();
```

returns 

```
TypeError: client.topics is not a function
```

I'll try to use the http api directly, but thought this may be a bug or documentation error. 

I'm using version `2.3.0` on node `18.17.1`

**Comment by ogzhanolguncu** [comment]
I'll try to reproduce and let you know.

**Comment by ogzhanolguncu** [comment]
Hey, sorry for the late reply. This is how you should use topics: client.topics.list(). They are not meant to be called like functions.

**Comment by mankins** [comment]
I went ahead an made a PR to fix the docs. Thanks for the help.

**Comment by ogzhanolguncu** [comment]
Thanks, I appreciate the effort.
